### ISSUE TITLE
Update Alldebrid - New API

### ISSUE THREAD

**Issue by Alldebrid** [tvaddonsco/tva-resolvers-repo#1]
Hello,

We are the Alldebrid development team.
We are contacting you to let you know that we have set up a new API.

All documentation is available here => https://docs.alldebrid.com/

Our old versions of our API are offline and we have been contacted by some users of your tool, that can't use it anymore with our service.

If you could check that out, that would be great.

Regards,
Alldebrid staff.

Edit ; let us know if you need anything !

**Comment by tvaddonsco** [comment]
Information received, looking into the issue.

**Comment by dzg** [comment]
Please please!
I use Alldebrid, and can't wait for you to update the script!
Thank you!

**Comment by tvaddonsco** [comment]
It's coming shortly!

**Comment by dzg** [comment]
It worked for me as of today! Thank you!
