### ISSUE TITLE
[URLResolver] - Why do we need to re-auhtorize Real Debrid after update

### ISSUE THREAD

**Issue by klyco** [tvaddonsco/tva-resolvers-repo#2]
Hi there!
Love your work, and thanks so much for continuing to keep URLResolver up and running!

I am wondering why we need to re-authorize RD after each update.  We didn't need to do for past updates.

Thanks!
KL

**Comment by tvaddonsco** [comment]
We're looking into it, we know Real-Debrid was under attack the other day, it might have something to do with that. Sorry for the inconvenience!
