### ISSUE TITLE
Remove Indigo as a dependency for URLResolver.

### ISSUE THREAD

**Issue by reddit-reaper** [tvaddonsco/tva-resolvers-repo#5]
That was a fucked up update. You sneaked in indigo as a dependency to URLResolver but only in the repo xml, you left it out of the code repository. That's not cool AT ALL.

**Comment by SerpentDrago** [comment]
Agree , Please remove any Dependency of Indigo . This is not cool at all

**Comment by DjDiabolik** [comment]
Indigo as useless in somecase..... REMOVE IT OR SET AS DEPENDECY OPTIONAL!
